### PR TITLE
Add fdroidRelease build type

### PR DESCRIPTION
**Pull request by proletarius101**
Since we (fdroid) don't have much capacity to manually update apps, and I've observed that you are not updating NekoX in fdroid manually actively, it's reasonable to enable full auto update by providing a universal APK

### CODE REVIEW

**Comment by luvletter2333** [comment]
Have you tested that this will compile a universal build?

**Comment by proletarius101** [comment]
Yes. It will not be with a "universal" in the file name, but it's a universal apk

**Comment by luvletter2333** [comment]
I think we need to refine the build configuration file such as Line 67 and Line 95.
For example, enable `universal` if it was a fdroid build in Line 93.

Could you try these changes? I’m absence from my computer these days and have no time to test it by myself.

**Comment by proletarius101** [comment]
`universalApk` is unnecessary as long as `splits.abi` is disabled (the same behavior before ABI splitting was introduced)

I change this pr to match the handling as seen in https://github.com/SagerNet/SagerNet/commit/7dfdc7ff622c443406d22a688689483a491066ac

**Comment by proletarius101** [comment]
Also, I only enable the `arm` and `arm64` variants, as what we do now, since the `x86` variant has blobs that need time to be investigated how to rebuild: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/516

**Comment by luvletter2333** [comment]
I have done this in bc309b21048d78db30855322369cd28a2259edf4.

Can you test these compile script in fdroid build ci?

```
  - versionName: 8.3.0-preview01
    versionCode: 500
    commit: bc309b21048d78db30855322369cd28a2259edf4
    timeout: 10800
    subdir: TMessagesProj
    submodules: true
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y ninja-build openjdk-11-jdk-headless
      - update-alternatives --auto java
    gradle:
      - miniFdroid
      - miniFdroid
    output: build/outputs/apk/mini/*/*.apk
    prebuild:
      - echo -e "\norg.gradle.jvmargs=-Xms1024m -Xmx4096m -XX:MaxPermSize=4096m" >>
        ../gradle.properties
      - pushd ..
      - ./run fdroid prebuild
    scandelete:
      - TMessagesProj
    build:
      - export NINJA_PATH=/usr/bin/ninja
      - pushd ..
      - ./run fdroid build
      - source bin/init/env.sh
      - go clean -cache
      - git rev-parse HEAD
      - git gc --prune=now
    ndk: r21e
```

**Comment by luvletter2333** [comment]
image

In my computer, I use `./gradlew TMessagesProj:assembleminiFdroidRelease` to compile this apk. It seems that the size of native libraries is correct and they don't contains debug symbols.

**Comment by proletarius101** [comment]
Still

```
C/C++: /home/vagrant/build/nekox.messenger/TMessagesProj/jni/voip/../c_utils.h:12:9: warning: 'LOGV' macro redefined [-Wmacro-redefined]
C/C++: /home/vagrant/build/nekox.messenger/TMessagesProj/jni/voip/libtgvoip/logging.h:28:9: note: previous definition is here
C/C++: In file included from /home/vagrant/build/nekox.messenger/TMessagesProj/jni/voip/tg_voip_jni.cpp:12:
C/C++: In file included from /home/vagrant/build/nekox.messenger/TMessagesProj/jni/voip/libtgvoip/VoIPServerConfig.h:13:
C/C++: /home/vagrant/build/nekox.messenger/TMessagesProj/jni/voip/libtgvoip/os/android/../../threading.h:110:8: warning: private field 'maxPriority' is not used [-Wunused-private-field]
C/C++: ninja: error: '/home/vagrant/build/nekox.messenger/TMessagesProj/jni/third_party/libvpx/source/libvpx/vpx_dsp/x86/libvpx_x86_yasm.a', needed by '/home/vagrant/build/nekox.messenger/TMessagesProj/build/intermediates/cxx/RelWithDebInfo/2e96063k/obj/x86/libtmessages.40.so', missing and no known rule to make it

> Task :TMessagesProj:buildCMakeRelWithDebInfo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':TMessagesProj:buildCMakeRelWithDebInfo'.
> Build command failed.
  Error while executing process /opt/android-sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/vagrant/build/nekox.messenger/TMessagesProj/.cxx/RelWithDebInfo/2e96063k/x86 tmessages.40}
  ninja: Entering directory `/home/vagrant/build/nekox.messenger/TMessagesProj/.cxx/RelWithDebInfo/2e96063k/x86'
  
  ninja: error: '/home/vagrant/build/nekox.messenger/TMessagesProj/jni/third_party/libvpx/source/libvpx/vpx_dsp/x86/libvpx_x86_yasm.a', needed by '/home/vagrant/build/nekox.messenger/TMessagesProj/build/intermediates/cxx/RelWithDebInfo/2e96063k/obj/x86/libtmessages.40.so', missing and no known rule to make it


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52m 40s
41 actionable tasks: 41 executed
==== detail end ====
2021-12-21 10:53:18,266 DEBUG: Error encoutered, stopping by user request.
==== detail end ====
2021-12-21 10:53:25,193 DEBUG: skip deploying full build logs: not enabled in config
2021-12-21 10:53:25,197 INFO: Finished
2021-12-21 10:53:25,198 INFO: 1 build failed
2021-12-21 10:53:25,221 DEBUG: skip deploying full build logs: not enabled in config
fdroid@buildserver-gcc136-public:~/fdroiddata$ 
```

Can you only enable the `arm` and `arm64` variants for fdroid as described at https://github.com/NekoX-Dev/NekoX/pull/692#issuecomment-997186225?

**Comment by luvletter2333** [comment]
This file is killed by Tfoss but we still keep it.

**Comment by luvletter2333** [comment]
or we cannot build x86 and x86_86 anymore, but I am going to try compiling this file from source

**Comment by proletarius101** [comment]
> or we cannot build x86 and x86_86 anymore, but I am going to try compiling this file from source

Or you may just use ABI filter to only build for `arm` and `arm64` before you find a way to build that `libvpx` from source? You can always remove the filter as long as you can build

**Comment by luvletter2333** [comment]
> 

Ok

**Comment by luvletter2333** [comment]
We can build libvpx_yasm for x86 and x86_64 now, This action has passed Native Builds 

https://github.com/NekoX-Dev/NekoX/actions/runs/1616345674

Commits from telegram-foss: ef1107f2f5949ee91a4a3025dbc28b7092956c11 and 0bed4a37d019a802ca0f8ff7a7f6ae1b593c84d4.

You need to add `apt install yasm -y` to the sudo part of the fdroid build script, which is required to build libvpx.

**Comment by proletarius101** [comment]
Thanks for your work!

Fixed in https://gitlab.com/fdroid/fdroiddata/-/commit/bf9a790a23970e04bdf04c345a86dbe44059f5a9#9fb96bb73c5c8b043a2cf0b2546019322138e1a2_791_790

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/nekox.messenger/505#site-footer It failed again.

**Comment by luvletter2333** [comment]
e4924c245a1169fd975b45e0eb85d8b13be671e1

This commit is not included in the build source, let me check the build script.

**Comment by luvletter2333** [comment]
Commit 6e60b3 is used, namely tag 8.3.0,which doesn’t contain fixes for fdroid build. I will make a new release today, please wait for it and use its new tag.

**Comment by linsui** [comment]
Thanks!

**Pull request closed without merging**
