### PR TITLE
upstream: bump version to v9.3.3

### PR DESCRIPTION
**Pull request by qwq233**
i haven't test fully so don't expect it too much
it can basically run but many NekoX feature propably  might be removed by accident in merge progress cuz i only fix build issues

### CODE REVIEW

**Comment by qwq233** [comment]
this is sample btw (miniDebug build with Android Debug signature)
https://cloud.qwq2333.top/s/SGzJ4rwyoswg9Pe
~~build progress is TOO annoyed btw~~

**Comment by JohnBetaro** [comment]
is there any plan to publish the next update on fdroid ?

**Comment by qwq233** [comment]
> is there any plan to publish the next update on fdroid ?

~~i am not developer tbh so idk~~
for me? no,i dont use fdroid and tbh i dont like it at all.
so the answer is no

**Comment by qwq233** [comment]
@luvletter2333 hello?

**Comment by selfmusing** [comment]
@qwq233

**Comment by selfmusing** [comment]
@qwq233

**Comment by luvletter2333** [comment]
Thanks for your helping :). I am back and will start to resolve the osmdroid map first.

**Comment by selfmusing** [comment]
> this is sample btw (miniDebug build with Android Debug signature) https://cloud.qwq2333.top/s/SGzJ4rwyoswg9Pe ~build progress is TOO annoyed btw~


can i also get latest debug version for testing? 
Screenshot_20230118-173707_Nekogram_X


Btw I'm using this one.

**Comment by qwq233** [comment]
@selfmusing The source code has been already there you can build for yourself

**Comment by selfmusing** [comment]
@qwq233 okay cool!

**Pull request merged**
