### PR TITLE
add test the fdroid version

### PR DESCRIPTION
**Pull request by proletarius101**
To find the bug in the upstream side earlier

### CODE REVIEW

**Comment by proletarius101** [comment]
This illustrated that the issue
````
> java.io.FileNotFoundException: /home/runner/work/NekoX/NekoX/TMessagesProj/.cxx/RelWithDebInfo/1m5z5k72/arm64-v8a/android_gradle_build.json (No such file or directory)
````
is caused by the upstream (here).

The solution is still unclear.

**Comment by luvletter2333** [comment]
Maybe caused by upgrading AGP 8.0, RelWithDebInfo was disabled in build.gradle because it breaks NekoX’s compilations in GitHub. I’m very sorry that it breaks fdroid build.

**Comment by luvletter2333** [comment]
https://github.com/NekoX-Dev/NekoX/commit/fb0a01b4d151cc39ab0a1b6e5bcfda1e47c8f0c1#diff-9c40bfd1692cc708287a4cf2b426780274416311b711de84b6299e3a6659ef7a

Could you run `export COMPILE_NATIVE=1` Before compiling in fdroid build script?
Or you can just use sed or other command to modify build.gradle 

https://github.com/NekoX-Dev/NekoX/blob/fb0a01b4d151cc39ab0a1b6e5bcfda1e47c8f0c1/TMessagesProj/build.gradle#L42


Make it always true

**Comment by luvletter2333** [comment]
But you may need to mention the size of the compiled APK file. It may contains useless native debug symbols

**Comment by luvletter2333** [comment]
And GitHub actions cannot compile fdroid version,I guess? 
Since it will use pre-compiled native libraries from actions cache but fdroid will build every thing from source code.

**Comment by proletarius101** [comment]
Thanks, I'll give it a try https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10133

> And GitHub actions cannot compile fdroid version,I guess?

You are right, this PR itself is not useful then.

**Comment by proletarius101** [comment]
Doesn't work... But if I turn https://github.com/NekoX-Dev/NekoX/blob/fb3a2b88fd7c37d356a423912846d385617128f3/TMessagesProj/build.gradle#L336-L338 into

````groovy
        if (((task.name.endsWith("Ndk") || task.name.startsWith("generateJsonModel") || task.name.startsWith("externalNativeBuild"))) && !(task.name.contains("Debug") || task.name.contains("Foss") )) {
            task.enabled = false
        }
````

It somehow works. Is it the correct way? @luvletter2333

**Comment by luvletter2333** [comment]
Umm, maybe yes. I have no idea about fdroid build, let’s see gitlab ci result.

**Comment by proletarius101** [comment]
Or

````
def disableCMakeRelWithDebInfo = false
````

**Comment by luvletter2333** [comment]
> Or
> 
> ```
> def disableCMakeRelWithDebInfo = false
> ```
> 
> (rather than `true` as you suggest) also works

Oh, I'm very very sorry, when the environment variable is set, this flag should be false.

**Comment by luvletter2333** [comment]
Setting it to false will allow gradle to compile native as needed.

**Comment by proletarius101** [comment]
> Oh, I'm very very sorry, when the environment variable is set, this flag should be false.

Thanks, I see. Then it's fixed~

**Pull request closed without merging**
